name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install OCI CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install oci-cli

      - name: Set up OCI CLI configuration
        run: |
          # Criação manual do arquivo de configuração do OCI CLI
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=$OCI_USER_OCID" >> ~/.oci/config
          echo "fingerprint=$OCI_FINGERPRINT" >> ~/.oci/config
          echo "tenancy=$OCI_TENANCY_OCID" >> ~/.oci/config
          echo "region=$OCI_REGION" >> ~/.oci/config
          echo "key_file=$HOME/private_key.pem" >> ~/.oci/config
          
          # Salvar chave privada no arquivo
          echo "$OCI_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Verificar se o arquivo de configuração foi gerado corretamente
          cat ~/.oci/config

          # Testar a configuração do OCI CLI
          oci --version
          oci os ns get

        env:
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Push Docker Image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag my-app:latest $DOCKER_USERNAME/my-app:latest
          docker push $DOCKER_USERNAME/my-app:latest

      - name: Push Docker Image to Oracle Container Registry
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
        run: |
          docker tag my-app:latest ${OCI_REGION}.ocir.io/my-namespace/my-app:latest
          echo $ORACLE_AUTH_TOKEN | docker login ${OCI_REGION}.ocir.io -u 'tenancy_namespace/username' --password-stdin
          docker push ${OCI_REGION}.ocir.io/my-namespace/my-app:latest

      - name: Deploy App on Oracle Cloud
        run: |
          echo "Custom deployment command"
