name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install OCI CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install oci-cli

      - name: Set up OCI CLI configuration
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=$OCI_USER_OCID" >> ~/.oci/config
          echo "fingerprint=$OCI_FINGERPRINT" >> ~/.oci/config
          echo "tenancy=$OCI_TENANCY_OCID" >> ~/.oci/config
          echo "region=$OCI_REGION" >> ~/.oci/config
          echo "$OCI_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          echo "key_file=$(pwd)/private_key.pem" >> ~/.oci/config
          cat ~/.oci/config
          oci --version
          oci os ns get

        env:
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}

      - name: Build Docker Image
        run: |
          docker build -t vini-energia-auth-service:latest .

      - name: Push Docker Image to Oracle Container Registry
        run: |
          cat "${OCI_PRIVATE_KEY}" | docker login ${OCI_REGION}.ocir.io -u "${OCI_NAMESPACE}/${OCI_USERNAME}" --password-stdin
          docker tag vini-energia-auth-service:latest ${OCI_REGION}.ocir.io/${OCI_NAMESPACE}/vini-energia-auth-service:latest
          docker push ${OCI_REGION}.ocir.io/${OCI_NAMESPACE}/vini-energia-auth-service:latest
        env:
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_NAMESPACE: ${{ secrets.OCI_NAMESPACE }}
          OCI_USERNAME: ${{ secrets.OCI_USERNAME }}

      - name: Deploy Docker Container on OCI Compute Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem opc@${OCI_COMPUTE_IP} <<EOF
            echo "${OCI_PRIVATE_KEY}" | docker login ${OCI_REGION}.ocir.io -u "${OCI_NAMESPACE}/${OCI_USERNAME}" --password-stdin
            docker pull ${OCI_REGION}.ocir.io/${OCI_NAMESPACE}/vini-energia-auth-service:latest
            docker run -d -p 80:8080 ${OCI_REGION}.ocir.io/${OCI_NAMESPACE}/vini-energia-auth-service:latest
          EOF
        env:
          OCI_COMPUTE_IP: ${{ secrets.OCI_COMPUTE_IP }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
